### ISSUE TITLE
Spike: investigate Grants Stack library

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/allo-v2#180]
**Timebox to half a day**

Spike on the library to support Grants Stack migration's to v2 — what tool / modules should we use?

**Comment by thelostone-mc** [comment]
- language: typescript
- output: node module 
- viem will be used for on-chain queries 
- explore having getters via subgraph 


We build keeping in mind to keep core and strategy pieces isolated so that we can split em out later in the future.
This will enable us to have 
- core library 
- every strategy could implement it's own library which relies on core library 


Functionality: 

**Registry**
Should implement all external / public functions at https://github.com/allo-protocol/allo-v2/blob/main/contracts/core/IRegistry.sol

**Allo**
Should implement all external / public functions at  https://github.com/allo-protocol/allo-v2/blob/main/contracts/core/IAllo.sol


*BaseStrategy**
Should implement all external / public functions at  https://github.com/allo-protocol/allo-v2/blob/main/contracts/strategies/IStrategy.sol

**DonationVotingMerkleStrategy**
Would internally use the functions defined by the BaseStrategy library functions
- https://github.com/allo-protocol/allo-v2/blob/main/contracts/strategies/donation-voting/DonationVotingStrategy.sol

**Comment by thelostone-mc** [comment]
TODO: create repo

**Comment by codenamejason** [comment]
> TODO:
> 
> * create repo + npm account

Do we have a paid account already for Allo?

**Comment by thelostone-mc** [comment]
> Do we have a paid NPM account already for Allo?

I think creating an npm account is free. 
We'll work this out once we have a shippable version 


@nfrgosselin 

Synced up with @gravityblast and it looks like the turbo eth isn't what grants-stack would need. 
We've started the repository over at https://github.com/allo-protocol/allo-v2-sdk
