### ISSUE TITLE
(spike) data handling recommendation

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/allo-v2#309]
**timebox to half a day**

We need to figure out how we want to handle data for AlloScan. Specifically:
- how we want to query the onchain / offchain data
- where we want to store the indexed data

The scope of this ticket is to research options and provide a recommendation back to the team on standup. Remember that we need to ship a completed project by Aug 22, so the proposed solution must fit into that appetite. 

**Resources:**
- [Shape-up doc](https://docs.google.com/document/d/1nDEFWMTYUNx147dJaY7DCxbt031F9ofVDGtQcmXRwdw/edit)
- [Miro planning board](https://miro.com/app/board/uXjVMnFEv8s=/?share_link_id=781896803122)

**Comment by thelostone-mc** [comment]
Data requirements is captured here: https://github.com/allo-protocol/allo-v2/issues/310#issuecomment-1713688570

**Comment by thelostone-mc** [comment]
Quick overview on why spec is the choice as opposed to other listed options:

Based on the requirements on what AlloScan requirements :

- track all transaction activities which happen on Registry and Allo
- being able to access / index off-chain data (from IPFS)
- being able to provide data quick across chain
- easy development/maintenance effort
- affordable where we are charged by indexing data and not API calls 
- ideally offer something reusable which can be used by other strategy builder to leverage what we offer and build on top of that 


Here is the listed comparison : 
 
<table>
<thead>
  <tr>
    <th>Topic</th>
    <th>fetch from chain</th>
    <th>subgraph </th>
    <th>spec</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>maintainance effort </td>
    <td>High Effort (dev-ops)<br><br><br>Have to maintain another service</td>
    <td>Medium Effort <br><br>As we support more strategies across more chains, <br>the schema becomes complicated, maintainance become difficult </td>
    <td>Low<br><br>We'll have to worry about simply supporting new strategies and this can be done creating a new Live object.<br>Code is cleaner and supports cross-chain so all data can be indexed in the same table<br></td>
  </tr>
  <tr>
    <td>development effort</td>
    <td>High Effort<br><br>Would require us to maintain another service all together which would have to be ground up using something like chain sauce.</td>
    <td>Medium<br><br><br>The boiler plate code and the inability to access off-chain data makes this quite complicated</td>
    <td>Easy<br><br>Removes all boiler plate code, as default events are auto indexed.<br>Only when data needs to be manipulated / we need access metadata would we write custom code </td>
  </tr>
  <tr>
    <td>Hosting effort</td>
    <td>High Effort<br><br>Would require a traditional web2 micro service running to offer endpoints to consume data.</td>
    <td>Low<br><br>Subgraph deploys are easy to maintain and publish </td>
    <td>Low<br><br><br>New tool, the deploy process is not documented but this should change soon.<br><br></td>
  </tr>
  <tr>
    <td>Testing effort</td>
    <td>Low Effort<br><br>Validating if the indexer is able to fetch info should by easy </td>
    <td>Low<br><br>Subgraph playground makes testing our logic very simple</td>
    <td>High<br><br>Testing requires working through the terminal and logginv via console which makes validating changes harder</td>
  </tr>
  <tr>
    <td>Data Indexed</td>
    <td>Medium Effort to make all data available<br><br>We can index all events via the ABI and adding custom logic to the data being indexed</td>
    <td>High effort to make all data available <br><br>We'll be forced to plan our data requirement and the index accordingly. <br>Any new change would require a redeplou</td>
    <td>Low Effort to make all data available<br><br>As all contract events are tracked automatically</td>
  </tr>
  <tr>
    <td>Making an API endpoint available</td>
    <td>High Effort</td>
    <td>Low Effort</td>
    <td>Medium Effort <br><br>Spec offers graph ql endpoints but we'll have to figure out the steps to go about this</td>
  </tr>
  <tr>
    <td>Support</td>
    <td>Low Support</td>
    <td>Medium Support discord channel</td>
    <td>High Support direct access to spec team</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</tbody>
</table>


Based on this , the recommendation right now would be build with spec as it would fulfill all the needs of allo-scan
Also since spec is a new
