### ISSUE TITLE
Scope out giveth integration contract

### ISSUE THREAD

**Issue by thelostone-mc** [allo-protocol/allo-v2#325]

**Comment by 0xKurt** [comment]
**Problem:**
> Mitch: "My intention is that we add it as an optional step into the project creation flow, user’s can opt-in to create an entry into the Gitcoin registry once they have completed creating their project on Giveth.
We will also add it into the flow for when a project receives its first recurring donation using SuperFluid since this is the original reason we needed it."


Giveth wants to create profiles in behalf of a user. Therefore we need a contract which handles profile creations on our Registry.
If the project owner wants to create the same profile on another chain itself, he should be able to create it with the same profile id and anchor.
In general the profile creation on different chains for the same project should always create the same profile id and anchor, independent of the msg.sender who calls the contract.

**Issues:** 
If a malicous actor create a profile in behalf of an owner and adds his address to the member list, he can act in the name of this project. To avoid this we could either: not allow seeting members or require a signature of the actual owner. the signed data need to include the member list.

**Issue we can't address:** if the owner of the project changes, we wouldn;t be able to re-create the same project with the new owner on a different chain


**Must have:**
- profile creation for an owner without members -> straight forward
- profile creation as owner with/without members -> straight forward
- unique nonce should be calculated using the owner and project name

- contract needs to be deployed to any chain at the same address (like using our deployer contract)
- test cases
- deploy script
- code review

Estimation: 2 day

**Nice to have:**
profile creation for an owner with members -> needs a signature, else a malicous actor could add itself as member
- test cases
Estimation: +1 day

**Open Questions:**
Where should the contract live? allo-v2 repo, or new repo?
Which chains does giveth support?

**Comment by 0xKurt** [comment]
@nfrgosselin

**Comment by 0xKurt** [comment]
Chains to deploy on:
Gnosis, Celo, Optimism, Mainnet, Polygon

**Comment by thelostone-mc** [comment]
- Explore deriving anchor address from owner and name (not msg sender and name) 
- Ensure members can be added when msg.sender == owner
